### ISSUE TITLE
Include Download Format mp4 (Video)

### ISSUE THREAD

**Issue by fernandobayit** [bappybd/python-music-downloader#1]
You can include to download the songs in mp4 (video) format. Including IDTags to videos as well.

**Comment by bappybd** [comment]
Yes I can add this feature. This script is still in early stage. Lots of clean up to do. I will add this feature in next couple of days if I get free time.

**Comment by bappybd** [comment]
@fernandogobah I have updated my script to download MP4 files. It is still in WIP. Check that out if its working for you. Currently MP4 conversion is very slow. I have also updated my script-name and usage parameters.

MP4 download command: python deezermusic -mp4 -playlist <deezer_playlist_id>
MP3 download command: python deezermusic -mp3 -playlist <deezer_playlist_id>

**Comment by fernandobayit** [comment]
Congratulations
